server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cskaoyanmall?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
pagehelper:
  helper-dialect: mysql
logging:
  level:
    com:
      cskaoyan:
        mall:
          mapper: debug
mybatis:
  type-handlers-package: com.cskaoyan.mall.handler
mall:
  aliyun:
    oss:
      bucket: cskaoyan
      end-point: oss-cn-beijing.aliyuncs.com
    sms:
      sign-name: 王道训练营
      template-code: SMS_173765187
      region-id: cn-hangzhou
    access-key-id: LTAI4Fr5gfYhcVjLMqeRGbuT
    access-secret: IrkcHu6dZyrjPZRushgO76P5392HJ1
